version: '3.8'
services:
  todo-app:
    build:
      context: ./app
    depends_on:
      - todo-database
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./app:/usr/src/app
      - node-modules-data:/usr/src/app/node_modules
    # develop:
    #   watch:
    #     - path: ./app/package.json
    #       action: rebuild
    #     - path: ./app
    #       target: /usr/src/app
    #       action: sync

  todo-database:
    image: mongo:6
    volumes: 
     - todo-volume:/data/db
     - mongo-config-data:/data/configdb
    ports:
      - 27017:27017

volumes:
  todo-volume:
    name: todo-volume
  mongo-config-data:
    name: mongo-config-data
  node-modules-data:
    name: node-modules-data